CREATE TABLE IF NOT EXISTS users (
 id BIGSERIAL PRIMARY KEY,
 username VARCHAR(100) UNIQUE NOT NULL,
 password VARCHAR(255) NOT NULL,
 role VARCHAR(30) NOT NULL
);
CREATE TABLE IF NOT EXISTS meeting_rooms (
 id BIGSERIAL PRIMARY KEY,
 name VARCHAR(150) NOT NULL,
 capacity INTEGER NOT NULL,
 location VARCHAR(150),
 equipment TEXT
);
CREATE TABLE IF NOT EXISTS bookings (
 id BIGSERIAL PRIMARY KEY,
 user_id BIGINT NOT NULL REFERENCES users(id),
 room_id BIGINT NOT NULL REFERENCES meeting_rooms(id),
 start_at TIMESTAMP NOT NULL,
 end_at TIMESTAMP NOT NULL,
 status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
 CHECK (start_at < end_at)
);
